//
// Copyright (C) 2024 Intel Corporation.
// SPDX-License-Identifier: Apache 2.0
//

#include "vpux/compiler/dialect/IE/IR/ops.hpp"
#include "vpux/compiler/dialect/VPU/IR/dialect.hpp"
#include "vpux/compiler/dialect/VPU/transforms/passes.hpp"
#include "vpux/compiler/dialect/VPU/utils/sep_utils.hpp"
#include "vpux/compiler/dialect/VPU/utils/setup_pipeline_options_utils.hpp"
#include "vpux/compiler/utils/analysis.hpp"
#include "vpux/utils/core/error.hpp"

namespace vpux::VPU {
#define GEN_PASS_DECL_SETUPENABLESEPTRSOPERATIONS
#define GEN_PASS_DEF_SETUPENABLESEPTRSOPERATIONS
#include "vpux/compiler/dialect/VPU/passes.hpp.inc"
}  // namespace vpux::VPU

using namespace vpux;

namespace {

//
// SetupEnableSEPtrsOperationsPass
//

class SetupEnableSEPtrsOperationsPass final :
        public VPU::impl::SetupEnableSEPtrsOperationsBase<SetupEnableSEPtrsOperationsPass> {
public:
    SetupEnableSEPtrsOperationsPass() = default;
    SetupEnableSEPtrsOperationsPass(const VPU::InitCompilerOptions& initCompilerOptions, Logger log)
            : _enableSEPtrsOperations(enableSEPtrsOperations),
              _enableExperimentalSEPtrsOperations(enableExperimentalSEPtrsOperations) {
        Base::initLogger(log, Base::getArgumentName());
        Base::copyOptionValuesFrom(initCompilerOptions);

        initializeFromOptions();
    }

private:
    mlir::LogicalResult initializeOptions(StringRef options) final;
    void safeRunOnModule() final;

private:
    // Initialize fields from pass options
    void initializeFromOptions();

private:
    bool _enableSEPtrsOperations = false;
    bool _enableExperimentalSEPtrsOperations = false;
    bool _allowCustomValues = false;
};

void addOption(mlir::OpBuilder optionsBuilder, IE::PipelineOptionsOp pipelineOptionsOp, mlir::StringRef optionName,
               size_t optionValue, bool allowCustomValues) {
    auto hasPipelineOption = pipelineOptionsOp.lookupSymbol<IE::OptionOp>(optionName) != nullptr;
    VPUX_THROW_WHEN(!allowCustomValues && hasPipelineOption,
                    "Enable SE pointers operations is already defined, probably you run '--init-compiler' twice");

    if (hasPipelineOption) {
        return;
    }
    auto* ctx = optionsBuilder.getContext();
    const auto constraintAttr = mlir::StringAttr::get(ctx, optionName);
    optionsBuilder.create<IE::OptionOp>(optionsBuilder.getUnknownLoc(), constraintAttr,
                                        mlir::BoolAttr::get(ctx, optionValue));
}

mlir::LogicalResult SetupEnableSEPtrsOperationsPass::initializeOptions(StringRef options) {
    if (mlir::failed(Base::initializeOptions(options))) {
        return mlir::failure();
    }

    initializeFromOptions();

    return mlir::success();
}

void SetupEnableSEPtrsOperationsPass::initializeFromOptions() {
    if (enableSEPtrsOperations.hasValue()) {
        _log.trace("Overloading the default value {0} of the '_EnableSEPtrsOperations' field to the value {1} "
                   "of the pass option 'EnableSEPtrsOperations' generated by MLIR",
                   _enableSEPtrsOperations, enableSEPtrsOperations);
        _enableSEPtrsOperations = enableSEPtrsOperations;
    }

    if (enableExperimentalSEPtrsOperations.hasValue()) {
        _log.trace(
                "Overloading the default value {0} of the '_enableExperimentalSEPtrsOperations' field to the value {1} "
                "of the pass option 'enableExperimentalSEPtrsOperations' generated by MLIR",
                _enableExperimentalSEPtrsOperations, enableExperimentalSEPtrsOperations);
        _enableExperimentalSEPtrsOperations = enableExperimentalSEPtrsOperations;
    }

    if (allowCustomValues.hasValue()) {
        _allowCustomValues = allowCustomValues.getValue();
    }
}

void SetupEnableSEPtrsOperationsPass::safeRunOnModule() {
    auto moduleOp = getModuleOp(getOperation());
    auto optionsBuilder = mlir::OpBuilder::atBlockBegin(moduleOp.getBody());
    auto pipelineOptionsOp = VPU::getPipelineOptionsOp(getContext(), moduleOp);
    optionsBuilder =
            mlir::OpBuilder::atBlockBegin(&pipelineOptionsOp.getOptions().front(), optionsBuilder.getListener());

    addOption(optionsBuilder, pipelineOptionsOp, VPU::ENABLE_SE_PTRS_OPERATIONS, _enableSEPtrsOperations,
              _allowCustomValues);
    addOption(optionsBuilder, pipelineOptionsOp, VPU::ENABLE_EXPERIMENTAL_SE_PTRS_OPERATIONS,
              _enableExperimentalSEPtrsOperations, _allowCustomValues);
}

}  // namespace

//
// createSetupEnableSEPtrsOperationsPass
//

std::unique_ptr<mlir::Pass> vpux::VPU::createSetupEnableSEPtrsOperationsPass() {
    return std::make_unique<SetupEnableSEPtrsOperationsPass>();
}

std::unique_ptr<mlir::Pass> vpux::VPU::createSetupEnableSEPtrsOperationsPass(
        const VPU::InitCompilerOptions& initCompilerOptions, Logger log) {
    return std::make_unique<SetupEnableSEPtrsOperationsPass>(initCompilerOptions, log);
}
