//
// Copyright (C) 2024 Intel Corporation.
// SPDX-License-Identifier: Apache 2.0
//

#include "vpux/compiler/dialect/IE/IR/ops.hpp"
#include "vpux/compiler/dialect/VPU/IR/dialect.hpp"
#include "vpux/compiler/dialect/VPU/transforms/factories/barrier_variant_constraint.hpp"
#include "vpux/compiler/dialect/VPU/transforms/passes.hpp"
#include "vpux/compiler/dialect/VPU/utils/wlm_constraint_utils.hpp"
#include "vpux/compiler/utils/analysis.hpp"
#include "vpux/utils/core/error.hpp"

namespace vpux::VPU {
#define GEN_PASS_DECL_SETUPNPUCONSTRAINT
#define GEN_PASS_DEF_SETUPNPUCONSTRAINT
#include "vpux/compiler/dialect/VPU/passes.hpp.inc"
}  // namespace vpux::VPU

using namespace vpux;

namespace {

//
// SetupNpuConstraintPass
//

class SetupNpuConstraintPass final : public VPU::impl::SetupNpuConstraintBase<SetupNpuConstraintPass> {
public:
    SetupNpuConstraintPass() = default;
    SetupNpuConstraintPass(const VPU::InitCompilerOptions& initCompilerOptions, Logger log)
            : _workloadManagementEnable(workloadManagementEnable) {
        Base::initLogger(log, Base::getArgumentName());
        Base::copyOptionValuesFrom(initCompilerOptions);

        initializeFromOptions();
    }

private:
    mlir::LogicalResult initializeOptions(StringRef options) final;
    void safeRunOnModule() final;

private:
    // Initialize fields from pass options
    void initializeFromOptions();

private:
    bool _workloadManagementEnable = false;
    bool _allowCustomValues = false;
};

void addConstraint(mlir::OpBuilder optionsBuilder, IE::PipelineOptionsOp pipelineOptionsOp,
                   mlir::StringRef constraintName, size_t constraintValue, bool allowCustomValues) {
    auto hasPipelineOption = pipelineOptionsOp.lookupSymbol<IE::OptionOp>(constraintName) != nullptr;
    VPUX_THROW_WHEN(!allowCustomValues && hasPipelineOption,
                    "Barrier constraint is already defined, probably you run '--init-compiler' twice");

    if (hasPipelineOption) {
        return;
    }

    auto* ctx = optionsBuilder.getContext();
    mlir::IntegerType sizeType = mlir::IntegerType::get(ctx, sizeof(void*) * 8, mlir::IntegerType::Unsigned);
    const auto constraintAttr = mlir::StringAttr::get(ctx, constraintName);
    optionsBuilder.create<IE::OptionOp>(optionsBuilder.getUnknownLoc(), constraintAttr,
                                        mlir::IntegerAttr::get(sizeType, constraintValue));
}

mlir::LogicalResult SetupNpuConstraintPass::initializeOptions(StringRef options) {
    if (mlir::failed(Base::initializeOptions(options))) {
        return mlir::failure();
    }

    initializeFromOptions();

    return mlir::success();
}

void SetupNpuConstraintPass::initializeFromOptions() {
    if (workloadManagementEnable.hasValue()) {
        _log.trace("Overloading the default value {0} of the '_workloadManagementEnable' field to the value {1} "
                   "of the pass option 'enableWorkloadManagement' generated by MLIR",
                   _workloadManagementEnable, workloadManagementEnable);
        _workloadManagementEnable = workloadManagementEnable;
    }

    if (wlmRollback.hasValue() && wlmRollback.getValue() == true) {
        // Using non-WLM values might result in slightly worse inference latency but is
        // safer in case compilation with WLM enabled fails
        _log.trace("Disabling partial workload management due to enabled WLM rollback");
        _workloadManagementEnable = false;
    }

    if (allowCustomValues.hasValue()) {
        _allowCustomValues = allowCustomValues.getValue();
    }
}

void SetupNpuConstraintPass::safeRunOnModule() {
    auto moduleOp = getModuleOp(getOperation());
    auto optionsBuilder = mlir::OpBuilder::atBlockBegin(moduleOp.getBody());
    auto pipelineOptionsOp = VPU::getPipelineOptionsOp(getContext(), moduleOp);
    optionsBuilder =
            mlir::OpBuilder::atBlockBegin(&pipelineOptionsOp.getOptions().front(), optionsBuilder.getListener());

    auto perBarrierVariantConstraint =
            vpux::VPU::getPerBarrierVariantConstraint(VPU::getArch(getOperation()), _workloadManagementEnable);
    auto barrVariantSum = perBarrierVariantConstraint.getPerBarrierMaxVariantSum();
    auto barrVariantCount = perBarrierVariantConstraint.getPerBarrierMaxVariantCount();

    addConstraint(optionsBuilder, pipelineOptionsOp, VPU::BARR_MAX_VARIANT_SUM, barrVariantSum, _allowCustomValues);
    addConstraint(optionsBuilder, pipelineOptionsOp, VPU::BARR_MAX_VARIANT_COUNT, barrVariantCount, _allowCustomValues);

    // Get Maximum available space in CMX Metadata for various descriptor types
    auto maxVariants = vpux::VPU::getDefaultTaskListCount(VPU::TaskType::DPUVariant, VPU::getArch(getOperation()));
    auto maxInvariants = vpux::VPU::getDefaultTaskListCount(VPU::TaskType::DPUInvariant, VPU::getArch(getOperation()));
    auto maxActKernelRange =
            vpux::VPU::getDefaultTaskListCount(VPU::TaskType::ActKernelRange, VPU::getArch(getOperation()));
    auto maxActKernelInvocation =
            vpux::VPU::getDefaultTaskListCount(VPU::TaskType::ActKernelInvocation, VPU::getArch(getOperation()));

    // Set CMX Metadata Constrains
    addConstraint(optionsBuilder, pipelineOptionsOp, VPU::METADATA_MAX_VARIANT_COUNT, maxVariants, _allowCustomValues);
    addConstraint(optionsBuilder, pipelineOptionsOp, VPU::METADATA_MAX_INVARIANT_COUNT, maxInvariants,
                  _allowCustomValues);
    addConstraint(optionsBuilder, pipelineOptionsOp, VPU::METADATA_MAX_KERNEL_INVOCATION_COUNT, maxActKernelInvocation,
                  _allowCustomValues);
    addConstraint(optionsBuilder, pipelineOptionsOp, VPU::METADATA_MAX_KERNEL_RANGE_COUNT, maxActKernelRange,
                  _allowCustomValues);
}

}  // namespace

//
// createSetupNpuConstraintPass
//

std::unique_ptr<mlir::Pass> vpux::VPU::createSetupNpuConstraintPass() {
    return std::make_unique<SetupNpuConstraintPass>();
}

std::unique_ptr<mlir::Pass> vpux::VPU::createSetupNpuConstraintPass(const VPU::InitCompilerOptions& initCompilerOptions,
                                                                    Logger log) {
    return std::make_unique<SetupNpuConstraintPass>(initCompilerOptions, log);
}
