//
// Copyright (C) 2024 Intel Corporation.
// SPDX-License-Identifier: Apache 2.0
//

#include "vpux/compiler/dialect/IE/IR/ops.hpp"
#include "vpux/compiler/dialect/VPU/IR/dialect.hpp"
#include "vpux/compiler/dialect/VPU/transforms/passes.hpp"
#include "vpux/compiler/dialect/VPU/utils/adaptive_stripping_utils.hpp"
#include "vpux/compiler/dialect/VPU/utils/setup_pipeline_options_utils.hpp"
#include "vpux/compiler/utils/analysis.hpp"
#include "vpux/utils/core/error.hpp"

namespace vpux::VPU {
#define GEN_PASS_DECL_SETUPENABLEADAPTIVESTRIPPING
#define GEN_PASS_DEF_SETUPENABLEADAPTIVESTRIPPING
#include "vpux/compiler/dialect/VPU/passes.hpp.inc"
}  // namespace vpux::VPU

using namespace vpux;

namespace {

//
// SetupEnableAdaptiveStrippingPass
//

class SetupEnableAdaptiveStrippingPass final :
        public VPU::impl::SetupEnableAdaptiveStrippingBase<SetupEnableAdaptiveStrippingPass> {
public:
    SetupEnableAdaptiveStrippingPass() = default;
    SetupEnableAdaptiveStrippingPass(const VPU::InitCompilerOptions& initCompilerOptions, Logger log)
            : _enableAdaptiveStripping(enableAdaptiveStripping) {
        Base::initLogger(log, Base::getArgumentName());
        Base::copyOptionValuesFrom(initCompilerOptions);

        initializeFromOptions();
    }

private:
    mlir::LogicalResult initializeOptions(StringRef options) final;
    void safeRunOnModule() final;

private:
    // Initialize fields from pass options
    void initializeFromOptions();

private:
    bool _enableAdaptiveStripping = false;
    bool _allowCustomValues = false;
};

void addOption(mlir::OpBuilder optionsBuilder, IE::PipelineOptionsOp pipelineOptionsOp, mlir::StringRef optionName,
               size_t optionValue, bool allowCustomValues) {
    auto hasPipelineOption = pipelineOptionsOp.lookupSymbol<IE::OptionOp>(optionName) != nullptr;
    VPUX_THROW_WHEN(!allowCustomValues && hasPipelineOption,
                    "Enable Adaptive Stripping is already defined, probably you run '--init-compiler' twice");

    if (hasPipelineOption) {
        return;
    }
    auto* ctx = optionsBuilder.getContext();
    const auto constraintAttr = mlir::StringAttr::get(ctx, optionName);
    optionsBuilder.create<IE::OptionOp>(optionsBuilder.getUnknownLoc(), constraintAttr,
                                        mlir::BoolAttr::get(ctx, optionValue));
}

mlir::LogicalResult SetupEnableAdaptiveStrippingPass::initializeOptions(StringRef options) {
    if (mlir::failed(Base::initializeOptions(options))) {
        return mlir::failure();
    }

    initializeFromOptions();

    return mlir::success();
}

void SetupEnableAdaptiveStrippingPass::initializeFromOptions() {
    if (enableAdaptiveStripping.hasValue()) {
        _log.trace("Overloading the default value {0} of the '_EnableAdaptiveStripping' field to the value {1} "
                   "of the pass option 'EnableAdaptiveStripping' generated by MLIR",
                   _enableAdaptiveStripping, enableAdaptiveStripping);
        _enableAdaptiveStripping = enableAdaptiveStripping;
    }

    if (allowCustomValues.hasValue()) {
        _allowCustomValues = allowCustomValues.getValue();
    }
}

void SetupEnableAdaptiveStrippingPass::safeRunOnModule() {
    auto moduleOp = getModuleOp(getOperation());
    auto optionsBuilder = mlir::OpBuilder::atBlockBegin(moduleOp.getBody());
    auto pipelineOptionsOp = VPU::getPipelineOptionsOp(getContext(), moduleOp);
    optionsBuilder =
            mlir::OpBuilder::atBlockBegin(&pipelineOptionsOp.getOptions().front(), optionsBuilder.getListener());

    addOption(optionsBuilder, pipelineOptionsOp, VPU::ENABLE_ADAPTIVE_STRIPPING, _enableAdaptiveStripping,
              _allowCustomValues);
}

}  // namespace

//
// createSetupEnableAdaptiveStrippingPass
//

std::unique_ptr<mlir::Pass> vpux::VPU::createSetupEnableAdaptiveStrippingPass() {
    return std::make_unique<SetupEnableAdaptiveStrippingPass>();
}

std::unique_ptr<mlir::Pass> vpux::VPU::createSetupEnableAdaptiveStrippingPass(
        const VPU::InitCompilerOptions& initCompilerOptions, Logger log) {
    return std::make_unique<SetupEnableAdaptiveStrippingPass>(initCompilerOptions, log);
}
