//
// Copyright (C) 2025-2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0
//

#include "vpux/compiler/dialect/VPU/transforms/passes.hpp"
#include "vpux/compiler/dialect/VPU/utils/cost_model/layer_vpunn_cost.hpp"
#include "vpux/compiler/dialect/VPU/utils/manual_strategy_utils.hpp"
#include "vpux/compiler/dialect/VPU/utils/tiling_algorithm/scf_tiling/scf_tiling.hpp"
#include "vpux/compiler/dialect/VPU/utils/tiling_algorithm/tiling_context.hpp"
#include "vpux/compiler/dialect/VPU/utils/tiling_pass_config_utils.hpp"
#include "vpux/compiler/dialect/VPU/utils/vertical_fusion/vertical_fusion_algorithm.hpp"
#include "vpux/compiler/dialect/VPU/utils/vertical_fusion/vertical_fusion_utils.hpp"
#include "vpux/compiler/dialect/config/IR/attributes.hpp"
#include "vpux/compiler/dialect/config/utils/config_option_utils.hpp"
#include "vpux/compiler/utils/attributes.hpp"
#include "vpux/utils/core/numeric.hpp"

#include <mlir/Transforms/DialectConversion.h>
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/Iterators.h"

namespace vpux::VPU {
#define GEN_PASS_DECL_SCFVERTICALFUSION
#define GEN_PASS_DEF_SCFVERTICALFUSION
#include "vpux/compiler/dialect/VPU/passes.hpp.inc"
}  // namespace vpux::VPU

using namespace vpux;
using namespace VPU;

namespace {

//
// SCFVerticalFusionPass
//

class SCFVerticalFusionPass final : public VPU::impl::SCFVerticalFusionBase<SCFVerticalFusionPass> {
public:
    SCFVerticalFusionPass(bool enableDynamicDimAlignment, const VFMergeConfiguration vfConf, Logger log)
            : _enableDynamicDimAlignment(enableDynamicDimAlignment), _vfMergeConfiguration(vfConf) {
        Base::initLogger(std::move(log), Base::getArgumentName());
    }

    mlir::LogicalResult initialize(mlir::MLIRContext* ctx) final;

private:
    void safeRunOnFunc() final;

    bool _enableDynamicDimAlignment = false;
    VFMergeConfiguration _vfMergeConfiguration;
};

mlir::LogicalResult SCFVerticalFusionPass::initialize(mlir::MLIRContext* ctx) {
    if (mlir::failed(Base::initialize(ctx))) {
        return mlir::failure();
    }
    if (enableDynamicDimAlignment.hasValue()) {
        _log.trace("Overloading SCFVerticalFusionPass argument by MLIR variable");
        _enableDynamicDimAlignment = enableDynamicDimAlignment.getValue();
    }

    if (vfMergeConfiguration.hasValue()) {
        _log.trace("Overloading the default value {0} of the '_vfMergeConfiguration' field to the value {1} of the "
                   "pass option 'vfMergeConfiguration' generated by MLIR",
                   _vfMergeConfiguration, vfMergeConfiguration.getValue());
        _vfMergeConfiguration = vfMergeConfiguration.getValue();
    }
    return mlir::success();
}

// prioretize merging operations, assuming that merged blocks are more benefitial
struct GreedyVFConfiguration : MergeConfiguration {
    GreedyVFConfiguration(Logger log) {
        splitGetter = [log](VPU::VF::v2::VFConfig& config, DimArrRef allowedDims) -> VPU::VF::v2::VFCase {
            auto vfSplit = VPU::VF::v2::getVFSplitForSCF(config, allowedDims);
            auto outputs = config.getOutputs();
            if (outputs.empty()) {
                return VPU::VF::v2::VFCase(config, {});
            }

            // E-164908 more than one output for VF to be supported
            auto* lastOp = outputs.back();

            VPUX_THROW_WHEN(lastOp->getNumResults() != 1,
                            "Expected single result for the last operation in the config, got {0}",
                            lastOp->getNumResults());
            auto outputType = mlir::cast<vpux::NDTypeInterface>(lastOp->getResult(0).getType());
            return VPU::VF::v2::computeVFSCFCase(outputType, vfSplit, config, lastOp, log);
        };
        mergeDecision = [](VPU::VF::v2::VFCase& vfCase) -> bool {
            return vfCase.isInitialized();
        };
        viewLikePolicy = [](mlir::Operation*) -> bool {
            // Allow view like operations in HostCompile pipeline
            return true;
        };
    }
};

// analize more split options and choose the most optimal one based on the cost function
// make decision to merge based on cost comparison between merged and non-merged cases
struct CostBasedVFConfiguration : MergeConfiguration {
    CostBasedVFConfiguration(const std::unique_ptr<VPU::LayerVPUNNCost>& costFunction, Logger log) {
        splitGetter = [&costFunction, log](VPU::VF::v2::VFConfig& config,
                                           DimArrRef allowedDims) -> VPU::VF::v2::VFCase {
            if (config.getOperationsForTiling().empty()) {
                return VPU::VF::v2::VFCase(config, {});
            }

            auto splits = VPU::VF::v2::getSplitFromDimArr(allowedDims, allowedDims, config,
                                                          /*enableMultiDimTiling=*/true);
            if (splits.empty()) {
                return VPU::VF::v2::VFCase(config, {});
            }

            const auto getMinTiles = [&](auto dim, const VPU::VF::v2::VFSplit& split) -> int64_t {
                if (split.size() > 1) {
                    return VPU::MIN_REQUIRED_TILES;
                }
                return VPU::VF::v2::getTilingLimit(dim, config) > 1 ? VPU::MIN_REQUIRED_TILES : 1;
            };

            const auto getMaxTiles = [&](auto dim, const VPU::VF::v2::VFSplit& split) -> int64_t {
                auto maxTiles = VPU::VF::v2::getTilingLimit(dim, config);
                if (split.size() > 1) {
                    auto otherDimSum = VPU::VF::v2::getVFTilesLen(split);
                    maxTiles = divUp(maxTiles, otherDimSum);
                }
                return maxTiles;
            };

            auto bestCase =
                    VPU::VF::v2::findBestVFCaseFromSplits(config, splits, getMinTiles, getMaxTiles, costFunction, log,
                                                          config.getOutputs().back()->getContext());

            if (!bestCase.has_value()) {
                return VPU::VF::v2::VFCase(config, {});
            }
            return std::move(bestCase.value());
        };

        // Sum of the standalone (unfused) costs of the given operations, each tiled with its own
        // assigned strategy. Used as the no-fusion reference for profitability decisions.
        const auto baselineOfOps = [&costFunction](ArrayRef<mlir::Operation*> ops) -> StrategyCost {
            return std::accumulate(
                    ops.begin(), ops.end(), StrategyCost{0}, [&costFunction](StrategyCost acc, mlir::Operation* op) {
                        SmallVector<int64_t> tilingDims;
                        if (auto tilingStrategyAttr =
                                    mlir::dyn_cast_or_null<mlir::ArrayAttr>(op->getAttr(tilingStrategy))) {
                            tilingDims = parseIntArrayAttr<int64_t>(tilingStrategyAttr);
                        }
                        return acc + VPU::VF::v2::extractBaselineCost(op, ShapeRef(tilingDims), costFunction,
                                                                      Logger::global());
                    });
        };
        const auto computeBaselineCost = [baselineOfOps](VPU::VF::v2::VFCase& vfCase) -> StrategyCost {
            return baselineOfOps(vfCase.getConfig().getOperationsForTiling());
        };

        mergeDecision = [&costFunction, log, computeBaselineCost](VPU::VF::v2::VFCase& vfCase) -> bool {
            if (!vfCase.isInitialized()) {
                return false;
            }

            const auto baselineCost = computeBaselineCost(vfCase);

            return VPU::VF::v2::isVFMergeProfitable(vfCase, baselineCost, 0, costFunction, log);
        };
        viewLikePolicy = [](mlir::Operation* op) -> bool {
            return VPU::VF::v2::isViewLikeOpVFCompatible(op);
        };
        // Pairwise marginal merge check used during incremental group growth in
        // collectTiledAndFusedOps. The incumbent is the current group; the candidate is the group
        // enlarged with one more producer. Accept the growth only when the fused cost of the enlarged
        // group is not greater than the current fused cost plus the standalone cost of the newly
        // added operations (merged <= previous + new). Mirrors the pairwise merge-profitability of the
        // default (non-SCF) VF path.
        selectBetterCase = [&costFunction, log, baselineOfOps](VPU::VF::v2::VFCase& current,
                                                               VPU::VF::v2::VFCase& candidate) -> bool {
            const auto fusedCost = [&](VPU::VF::v2::VFCase& vfCase) -> int64_t {
                return checked_cast<int64_t>(vfCase.getCost(costFunction, log));
            };

            const auto& currentOps = current.getConfig().getVFOperations();
            const auto& candidateOps = candidate.getConfig().getVFOperations();

            // Operations the candidate adds on top of the current group.
            std::vector<mlir::Operation*> newOps;
            newOps.reserve(candidateOps.size());
            std::set_difference(candidateOps.begin(), candidateOps.end(), currentOps.begin(), currentOps.end(),
                                std::back_inserter(newOps));

            if (newOps.empty()) {
                // Same operation set: keep whichever tiling yields the lower fused cost.
                return fusedCost(candidate) < fusedCost(current);
            }

            const auto newOpsStandaloneCost = checked_cast<int64_t>(baselineOfOps(newOps));

            // Grow only when fusing the new operations is not more expensive than running the current
            // group and the new operations separately.
            return fusedCost(candidate) <= fusedCost(current) + newOpsStandaloneCost;
        };

        vfOpsRestriction = [](mlir::Operation* op) -> bool {
            return mlir::isa<VPU::VerticalFusionOpInterface>(op);
        };
    }
};

//
// safeRunOnFunc
//

void SCFVerticalFusionPass::safeRunOnFunc() {
    auto& ctx = getContext();
    auto func = getOperation();
    mlir::OpBuilder builder(&ctx);
    mlir::IRRewriter irBuilder(builder);

    llvm::SetVector<mlir::Operation*> fusedOps;

    if (_enableDynamicDimAlignment) {
        VPU::setDynamicDimAlignment(func);
    }

    std::unique_ptr<VPU::LayerVPUNNCost> costFunction;
    MergeConfiguration mergeConfig;
    switch (_vfMergeConfiguration) {
    case VFMergeConfiguration::COST_BASED: {
        auto module = func->getParentOfType<mlir::ModuleOp>();
        auto maybeLayerCostModelAnalysis = getCachedParentAnalysis<VPU::LayerCostModelAnalysis>(module);
        auto layerCostModel =
                VPU::LayerCostModelAnalysis::getOrCreateLayerCostModel(maybeLayerCostModelAnalysis, &ctx, _log);
        costFunction = std::make_unique<VPU::LayerVPUNNCost>(func, layerCostModel, _log);
        mergeConfig = CostBasedVFConfiguration(costFunction, _log);
        break;
    }
    case VFMergeConfiguration::GREEDY:
        mergeConfig = GreedyVFConfiguration(_log);
        break;
    default:
        VPUX_THROW("Unsupported VF merge configuration");
    }

    func->walk<mlir::WalkOrder::PostOrder, mlir::ReverseIterator>([&](mlir::TilingInterface operation) {
        auto* op = operation.getOperation();

        if (fusedOps.contains(op)) {
            _log.nest().trace("Operation has already been fused");
            return;
        }

        if (!op->hasAttr(tilingStrategy)) {
            _log.nest().trace("No tiling strategy or it has already been applied.");
            return;
        }

        const auto options = VPU::TilingContextOptions(VPU::TilingContextOptions::ContextType::TILING,
                                                       /* enableSCFTiling = */ true);
        auto tilingContext = VPU::createTilingContext(op, options);
        _log.nest().trace("Applying SCF Tiling and Fusion for the operation: {0}", *op);
        const auto fused = tilingContext.applySCFTilingAndFusion(irBuilder, mergeConfig, _log);

        if (!fused.empty()) {
            fusedOps.insert(fused.begin(), fused.end());
        } else {
            _log.nest().trace("No fusion applied for the operation: {0}", *op);
        }
    });

    // remove dynamic alignment
    VPU::removeDynamicDimAlignment(func);
}

}  // namespace

//
// createSCFVerticalFusionPass
//

std::unique_ptr<mlir::Pass> VPU::createSCFVerticalFusionPass(const VFMergeConfiguration vfConf,
                                                             bool enableDynamicDimAlignment, Logger log) {
    return std::make_unique<SCFVerticalFusionPass>(enableDynamicDimAlignment, vfConf, log);
}
