name: 'Download Models'
description: 'Download models from different sources'

inputs:
  compiler-type:
    description: 'MLIR|DRIVER'
    type: string
    required: true
  models-config:
    description: 'Path to a JSON configuration file describing models to validate'
    type: string
    required: true
  models-dir:
    description: 'Path to a directory where to save models'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup python version
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: '3.13'

    - name: Install dependencies
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --require-hashes -r ${{ github.action_path }}/requirements.txt

    - name: Run downloader script
      shell: bash
      run: |
        python3 ${{ github.action_path }}/download_models.py \
          --compiler-type "${{ inputs.compiler-type }}" \
          --models-config "${{ inputs.models-config }}" \
          --models-dir "${{ inputs.models-dir }}"
