name: clang-format
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
      - releases/**

concurrency:
  group: clang-format-${{ github.event_name }}-${{ github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions: read-all

jobs:
  clang-format:
    runs-on: ubuntu-latest-8-cores
    steps:
      - name: Checkout NPU Compiler
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup python version
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
            python-version: '3.14'

      - name: Run clang-format via pre-commit (pull_request)
        if: github.event_name == 'pull_request'
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: >
            clang-format
            --show-diff-on-failure
            --from-ref ${{ github.event.pull_request.base.sha }}
            --to-ref ${{ github.event.pull_request.head.sha }}

      - name: Run clang-format via pre-commit (push)
        if: github.event_name != 'pull_request'
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: >
            clang-format
            --show-diff-on-failure
            --all-files
