name: clang-format
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

concurrency:
  group: clang-format-${{ github.event_name }}-${{ github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions: read-all

jobs:
  clang-format:
    runs-on: ubuntu-latest-8-cores
    steps:
      - name: Checkout NPU Compiler
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup python version
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
            python-version: '3.13'

      - name: Run clang-format via pre-commit (pull_request)
        if: github.event_name == 'pull_request'
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: >
            clang-format
            --show-diff-on-failure
            --from-ref ${{ github.event.pull_request.base.sha }}
            --to-ref ${{ github.event.pull_request.head.sha }}

      - name: Run clang-format via pre-commit (push)
        if: github.event_name != 'pull_request'
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: >
            clang-format
            --show-diff-on-failure
            --all-files
