name: Linux MLIR Build
on:
  workflow_call:
    inputs:
      os:
        description: 'OS that is used for building in the form of "ubuntu_20_04"'
        type: string
        required: true
      build-runner:
        description: 'Machine on which the builds will run'
        type: string
        required: true
      openvino-cmake-options:
        description: 'A string of options passed to OpenVINO CMake'
        type: string
        required: false
      npu-cmake-options:
        description: 'A string of options passed to NPU Compiler CMake'
        type: string
        required: false
      build-cache:
        description: 'Whether to take previously built OpenVINO/NPU package'
        type: boolean
        required: false
        default: false
      build-cache-key-suffix:
        description: 'Cache package suffix'
        type: string
        required: false
      with-codeql:
        description: 'Whether to run CodeQL static C/C++ analyzer'
        type: boolean
        required: false
        default: false
      with-tests:
        description: 'Whether to build test targets'
        type: boolean
        required: false
        default: false
    outputs:
      build-package:
        description: 'OpenVINO/NPU build package name to be stored as the action artifact'
        value: ${{ jobs.Build.outputs.build-package }}

defaults:
  run:
    shell: bash

permissions:
  actions: read
  contents: read
  packages: read
  statuses: read

jobs:
  Build:
    name: Build
    runs-on: ${{ inputs.build-runner }}
    timeout-minutes: 240
    permissions:
      actions: read
      contents: read
      packages: read
      statuses: read
      security-events: write
    outputs:
      build-package: ${{ steps.set-build-package-name.outputs.build-package }}
    env:
      DEBIAN_FRONTEND: noninteractive
      CMAKE_BUILD_TYPE: 'Release'
      OPENVINO_REPO: ./openvino
      NPU_ACTIONS_DIR: ./npu_actions
      NPU_COMPILER_REPO: ./npu_compiler
      OPENVINO_BUILD_DIR: ./openvino_build
      NPU_COMPILER_BUILD_DIR: ./npu_compiler_build
      OPENVINO_INSTALL_DIR: ./openvino_install
      OPENVINO_BUILD_PACKAGE: l_ov_dyn_${{ inputs.os }}_npu_${{ github.sha }}
      CODEQL_OUTPUTS: ./codeql_outputs
      CODEQL_ARTIFACT_NAME: l_codeql_${{ inputs.os }}_npu_${{ github.sha }}
    steps:
      - name: Get cache key
        if: ${{ inputs.build-cache }}
        id: cache-key
        run: |
          cache_key="l_ov_dyn_${{ inputs.os }}_cache_${{ inputs.build-cache-key-suffix || github.sha }}"
          echo "cache-key=$cache_key" >> $GITHUB_OUTPUT

      - name: Restore OpenVINO/NPU package from cache
        if: ${{ inputs.build-cache }}
        id: cache-restore
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          key: ${{ steps.cache-key.outputs.cache-key }}
          path: ${{ env.OPENVINO_INSTALL_DIR }}

      - name: Checkout versions action
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          path: ${{ env.NPU_ACTIONS_DIR }}
          sparse-checkout: |
            .github/actions/versions
          sparse-checkout-cone-mode: false

      - name: Get versions
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        uses: ./npu_actions/.github/actions/versions
        id: versions

      - name: Clone OpenVINO
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        timeout-minutes: 15
        with:
          repository: ${{ steps.versions.outputs.openvino-repository }}
          path: ${{ env.OPENVINO_REPO }}
          submodules: true
          ref: ${{ steps.versions.outputs.openvino-sha }}

      - name: Clone NPU Compiler
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        timeout-minutes: 15
        with:
          path: ${{ env.NPU_COMPILER_REPO }}
          submodules: true
          lfs: true

      - name: System info
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        uses: openvinotoolkit/openvino/.github/actions/system_info@44526285f241251e9543276572676365fbe542a4 # 2025.3.0

      - name: Setup python version
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.13'

      - name: Install python dependencies
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: |
          python3 -m pip install --require-hashes -r ${NPU_COMPILER_REPO}/.github/requirements-dev.txt

      - name: Prepare environment
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: |
          if [[ "${{ inputs.with-tests }}" == "true" ]]; then
            echo "ENABLE_TESTS_FLAG=ON" >> $GITHUB_ENV
          else
            echo "ENABLE_TESTS_FLAG=OFF" >> $GITHUB_ENV
          fi

      - name: Initialize CodeQL
        if: ${{ !steps.cache-restore.outputs.cache-hit && inputs.with-codeql }}
        uses: github/codeql-action/init@e12f0178983d466f2f6028f5cc7a6d786fd97f4b # v4.31.4
        with:
          languages: c-cpp
          build-mode: manual
          source-root: ${{ env.NPU_COMPILER_REPO }}

      - name: CMake configure - OpenVINO
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: |
          cmake \
            ${{ inputs.openvino-cmake-options }} \
            -G "Ninja Multi-Config" \
            -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} \
            -DENABLE_LTO=OFF \
            -DENABLE_TESTS=${{ env.ENABLE_TESTS_FLAG }} \
            -DENABLE_INTEL_CPU=${{ env.ENABLE_TESTS_FLAG }} \
            -DENABLE_INTEL_GPU=${{ env.ENABLE_TESTS_FLAG }} \
            -DENABLE_INTEL_NPU=ON \
            -DENABLE_IMD_BACKEND=OFF \
            -DENABLE_ONEDNN_FOR_GPU=OFF \
            -DENABLE_AUTO=ON \
            -DENABLE_AUTO_BATCH=ON \
            -DENABLE_HETERO=ON \
            -DENABLE_MULTI=ON \
            -DENABLE_TEMPLATE=ON \
            -DENABLE_OV_ONNX_FRONTEND=ON \
            -DENABLE_OV_PADDLE_FRONTEND=ON \
            -DENABLE_OV_TF_FRONTEND=ON \
            -DENABLE_OV_TF_LITE_FRONTEND=OFF \
            -DENABLE_OV_IR_FRONTEND=ON \
            -DENABLE_MLIR_COMPILER=ON \
            -DENABLE_PLUGINS_XML=ON \
            -DENABLE_PYTHON=ON \
            -DENABLE_WHEEL=OFF \
            -DENABLE_TBBBIND_2_5=ON \
            -DENABLE_DEBUG_CAPS=ON \
            -DENABLE_NPU_DEBUG_CAPS=ON \
            -DENABLE_SANITIZER=OFF \
            -DENABLE_THREAD_SANITIZER=OFF \
            -DENABLE_UB_SANITIZER=OFF \
            -S ${OPENVINO_REPO} \
            -B ${OPENVINO_BUILD_DIR}

      - name: CMake build - OpenVINO
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: |
          cmake --build ${OPENVINO_BUILD_DIR} --parallel $(nproc) --config ${{ env.CMAKE_BUILD_TYPE }}

      - name: CMake install - OpenVINO
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: |
          cmake --install ${OPENVINO_BUILD_DIR} --config ${{ env.CMAKE_BUILD_TYPE }} --prefix ${OPENVINO_INSTALL_DIR}
          cmake --install ${OPENVINO_BUILD_DIR} --config ${{ env.CMAKE_BUILD_TYPE }} --prefix ${OPENVINO_INSTALL_DIR} --component python_wheels
          cmake --install ${OPENVINO_BUILD_DIR} --config ${{ env.CMAKE_BUILD_TYPE }} --prefix ${OPENVINO_INSTALL_DIR} --component tests
          cmake --install ${OPENVINO_BUILD_DIR} --config ${{ env.CMAKE_BUILD_TYPE }} --prefix ${OPENVINO_INSTALL_DIR} --component developer_package

      - name: CMake configure - NPU Compiler
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: |
          cmake \
            ${{ inputs.npu-cmake-options }} \
            -G "Ninja Multi-Config" \
            -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} \
            -DOpenVINODeveloperPackage_DIR=$(realpath ${OPENVINO_BUILD_DIR}) \
            -DENABLE_TESTS=${{ env.ENABLE_TESTS_FLAG }} \
            -DENABLE_DEVELOPER_BUILD=ON \
            -DENABLE_MLIR_COMPILER=ON \
            -DBUILD_COMPILER_FOR_DRIVER=OFF \
            -DENABLE_DRIVER_COMPILER_ADAPTER=ON \
            -DENABLE_SOURCE_PACKAGE=OFF \
            -S ${NPU_COMPILER_REPO} \
            -B ${NPU_COMPILER_BUILD_DIR}

      - name: CMake build - NPU Compiler
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: |
          cmake --build ${NPU_COMPILER_BUILD_DIR} --parallel $(nproc) --config ${{ env.CMAKE_BUILD_TYPE }}

      - name: CMake install - NPU Compiler
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: |
          cmake --install ${NPU_COMPILER_BUILD_DIR} --config ${{ env.CMAKE_BUILD_TYPE }} --prefix ${OPENVINO_INSTALL_DIR}
          cmake --install ${NPU_COMPILER_BUILD_DIR} --config ${{ env.CMAKE_BUILD_TYPE }} --prefix ${OPENVINO_INSTALL_DIR} --component tests

      - name: Perform CodeQL Analysis
        id: codeql-analyze
        if: ${{ !steps.cache-restore.outputs.cache-hit && inputs.with-codeql }}
        uses: github/codeql-action/analyze@e12f0178983d466f2f6028f5cc7a6d786fd97f4b # v4.31.4
        with:
          category: "/language:c-cpp"
          output: ${{ env.CODEQL_OUTPUTS }}
          upload: failure-only
          checkout_path: ${{ env.NPU_COMPILER_REPO }}

      - name: Filter CodeQL results
        id: codeql-filtered-analyze
        if: ${{ !steps.cache-restore.outputs.cache-hit && inputs.with-codeql }}
        uses: advanced-security/filter-sarif@f3b8118a9349d88f7b1c0c488476411145b6270d # Release 1.0
        with:
          input: ${{ env.CODEQL_OUTPUTS }}/cpp.sarif
          output: ${{ env.CODEQL_OUTPUTS }}/filtered-results.sarif
          patterns: |
            +**
            -thirdparty/flatbuffers/**
            -thirdparty/gtest-parallel/**
            -thirdparty/llvm-project/**
            -thirdparty/yaml-cpp/**

      - name: Upload CodeQL SARIF
        if: ${{ !steps.cache-restore.outputs.cache-hit && inputs.with-codeql }}
        uses: github/codeql-action/upload-sarif@e12f0178983d466f2f6028f5cc7a6d786fd97f4b # v4.31.4
        with:
          sarif_file: ${{ env.CODEQL_OUTPUTS }}/filtered-results.sarif
          checkout_path: ${{ env.NPU_COMPILER_REPO }}

      - name: Upload CodeQL loc as a Build Artifact
        if: ${{ !steps.cache-restore.outputs.cache-hit && inputs.with-codeql }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ${{ env.CODEQL_ARTIFACT_NAME }}
          path: ${{ env.CODEQL_OUTPUTS }}
          retention-days: 1

      - name: Cache artifacts
        if: ${{ inputs.build-cache && !steps.cache-restore.outputs.cache-hit }}
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ${{ env.OPENVINO_INSTALL_DIR }}
          key: ${{ steps.cache-key.outputs.cache-key }}

      - name: Upload artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          path: ${{ env.OPENVINO_INSTALL_DIR }}
          name: ${{ env.OPENVINO_BUILD_PACKAGE }}

      - name: Set build package name to outputs
        id: set-build-package-name
        run: |
          echo ${OPENVINO_BUILD_PACKAGE}
          echo "build-package=l_ov_dyn_${{ inputs.os }}_npu_${{ github.sha }}" >> $GITHUB_OUTPUT
