name: Linux Compilation Tests
on:
  workflow_call:
    inputs:
      os:
        description: 'OS that is used for building in the form of "ubuntu_20_04"'
        type: string
        required: true
      test-runner:
        description: 'Machine on which the tests will run'
        type: string
        required: true
      install-package:
        description: 'Artifacts name from the build stage. Content varies depending on compiler-type'
        type: string
        required: true
      compiler-type:
        description: 'MLIR or DRIVER'
        type: string
        required: true
      export-blobs:
        description: 'Whether to upload compiled models as the job artifact'
        type: boolean
        required: false
        default: false

defaults:
  run:
    shell: bash

permissions:
  actions: read
  contents: read
  packages: read
  statuses: read

jobs:
  CompilationTests:
    name: Compilation tests ${{ inputs.compiler-type }} ${{ matrix.npu-platform }}
    runs-on: ${{ inputs.test-runner }}
    timeout-minutes: 60
    env:
      INSTALL_PACKAGE_DIR: ./install_package
      MODELS_DIR: ./models
      BLOBS_DIR: ./blobs
      BLOBS_ARTIFACT_NAME: l_compile_blobs_${{ inputs.os }}_${{ matrix.npu-platform }}_${{ inputs.compiler-type }}_${{ github.sha }}
      LOGS_DIR: ./logs
      LOGS_ARTIFACT_NAME: l_compile_logs_${{ inputs.os }}_${{ matrix.npu-platform }}_${{ inputs.compiler-type }}_${{ github.sha }}
    strategy:
      fail-fast: false
      matrix:
        npu-platform:
          - NPU.3720
          - NPU.4000
          - NPU.5010
        compiler-mode: 
          - ${{ inputs.compiler-type }}
        include:
          - npu-platform: NPU.3720
            models-config: ./validation/public_models_3720_${{ inputs.compiler-type }}.json
          - npu-platform: NPU.4000
            models-config: ./validation/public_models_4000_${{ inputs.compiler-type }}.json
          - npu-platform: NPU.5010
            models-config: ./validation/public_models_5010_${{ inputs.compiler-type }}.json
    steps:
      - name: Checkout
        if: ${{ !(matrix.npu-platform == 'NPU.5010' && inputs.compiler-type == 'DRIVER') }}
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Download artifacts
        if: ${{ !(matrix.npu-platform == 'NPU.5010' && inputs.compiler-type == 'DRIVER') }}
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53  # v6.0.0
        with:
          name: ${{ inputs.install-package }}
          path: ${{ env.INSTALL_PACKAGE_DIR }}

      - name: Unpack Driver artifacts
        if: ${{ inputs.compiler-type == 'DRIVER' && !(matrix.npu-platform == 'NPU.5010') }}
        run: |
          cd ${INSTALL_PACKAGE_DIR}
          dpkg --extract external/intel-driver-compiler-npu_*.deb .
          dpkg --extract external/intel-level-zero-npu_*.deb .
          dpkg --extract internal/intel-level-zero_*.deb .
          dpkg --extract internal/intel-openvino-npu_*.deb .
          find . -type f

      - name: Install system packages
        if: ${{ inputs.compiler-type == 'DRIVER' && !(matrix.npu-platform == 'NPU.5010') }}
        run: |
          sudo apt update
          sudo apt install -y libtbb12

      - name: Download models for ${{ matrix.npu-platform }}
        if: ${{ !(matrix.npu-platform == 'NPU.5010' && inputs.compiler-type == 'DRIVER') }}
        uses: ./.github/actions/download-models
        with:
          compiler-type: ${{ inputs.compiler-type }}
          models-config: ${{ matrix.models-config }}
          models-dir: ${{ env.MODELS_DIR }}

      - name: Compile models for ${{ matrix.npu-platform }}
        if: ${{ !(matrix.npu-platform == 'NPU.5010' && inputs.compiler-type == 'DRIVER') }}
        uses: ./.github/actions/compile-models
        with:
          compiler-type: ${{ inputs.compiler-type }}
          npu-platform: ${{ matrix.npu-platform }}
          install-package-dir: ${{ env.INSTALL_PACKAGE_DIR }}
          models-dir: ${{ env.MODELS_DIR }}
          blobs-dir: ${{ env.BLOBS_DIR }}
          models-config: ${{ matrix.models-config }}
          logs-dir: ${{ env.LOGS_DIR }}

      - name: Upload logs artifacts
        if: ${{ always() && env.LOGS_DIR }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          path: ${{ env.LOGS_DIR }}
          name: ${{ env.LOGS_ARTIFACT_NAME }}

      - name: Upload blobs artifacts
        if: ${{ always() && inputs.export-blobs && env.BLOBS_DIR }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          path: ${{ env.BLOBS_DIR }}
          name: ${{ env.BLOBS_ARTIFACT_NAME }}
