name: Windows NPU CiD Build
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      os:
        description: 'OS that is used for building in the form of "windows_2022"'
        type: string
        required: true
      build-runner:
        description: 'Machine on which the builds will run'
        type: string
        required: true
      openvino-cmake-options:
        description: 'Extra OpenVINO CMake options (appended last)'
        type: string
        required: false
      build-cache:
        description: 'Cache produced CiD artifact directory'
        type: boolean
        required: false
        default: false
      build-cache-key-suffix:
        description: 'Cache key suffix'
        type: string
        required: false
      tbb-root:
        description: 'Custom TBB root (optional). If set, passed as -DTBBROOT='
        type: string
        required: false
      publish-release-assets:
        description: 'The workflow will find a release tag associated with the commit and push the release asset.'
        type: boolean
        required: false
        default: false
    outputs:
      build-package:
        description: 'Produced CiD artifact name (uploaded artifact)'
        value: ${{ jobs.Build.outputs.build-package }}
    secrets:
      release_token:
        description: 'PAT with Contents: read/write'
        required: false

defaults:
  run:
    shell: bash

permissions:
  actions: read
  contents: read
  packages: read
  statuses: read

jobs:
  Build:
    name: Build
    runs-on: ${{ inputs.build-runner }}
    timeout-minutes: 240
    permissions:
      actions: read
      contents: read
      packages: read
      statuses: read
    outputs:
      build-package: ${{ steps.set-build-package-name.outputs.build-package }}
    env:
      DEBIAN_FRONTEND: noninteractive
      CMAKE_BUILD_TYPE: Release
      OPENVINO_REPO: ./openvino
      NPU_ACTIONS_DIR: ./npu_actions
      NPU_COMPILER_REPO: ./npu_compiler
      OPENVINO_BUILD_DIR: ./openvino_build
      CID_PACKAGE_ARTIFACTS_DIR: ./cid_artifacts
      CID_PACKAGE_BASE_NAME: w_cid_${{ inputs.os }}_${{ github.sha }}
      CID_PACKAGE_FULL_NAME: w_cid_${{ inputs.os }}_${{ github.sha }}.zip

    steps:
      - name: Prepare artifact dir
        run: cmake -E make_directory "${CID_PACKAGE_ARTIFACTS_DIR}"

      - name: Get cache key
        if: ${{ inputs.build-cache }}
        id: cache-key
        run: |
          cache_key="w_cid_${{ inputs.os }}_cache_${{ inputs.build-cache-key-suffix || github.sha }}"
          echo "cache-key=$cache_key" >> $GITHUB_OUTPUT

      - name: Restore CiD artifacts from cache
        if: ${{ inputs.build-cache }}
        id: cache-restore
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          key: ${{ steps.cache-key.outputs.cache-key }}
          path: ${{ env.CID_PACKAGE_ARTIFACTS_DIR }}

      - name: Checkout versions action
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: ${{ env.NPU_ACTIONS_DIR }}
          sparse-checkout: |
            .github/actions/versions
          sparse-checkout-cone-mode: false

      - name: Get versions
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        uses: ./npu_actions/.github/actions/versions
        id: versions

      - name: Clone OpenVINO
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        timeout-minutes: 15
        with:
          repository: ${{ steps.versions.outputs.openvino-repository }}
          path: ${{ env.OPENVINO_REPO }}
          submodules: true
          ref: ${{ steps.versions.outputs.openvino-sha }}

      - name: Checkout NPU Compiler
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: ${{ env.NPU_COMPILER_REPO }}
          submodules: true
          lfs: true

      - name: System info
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        uses: openvinotoolkit/openvino/.github/actions/system_info@c01cd93e24d1cd78bfbb401eed51c08fb93e0816 # 2025.2.0

      - name: Setup python version
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.13'

      - name: Install python deps
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: |
          python -m pip install --require-hashes -r ${NPU_COMPILER_REPO}/.github/requirements-dev.txt

      - name: Setup MSVC env (x64)
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          arch: x64

      - name: Prepare environment
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        env:
          TBB_ROOT_OPT: ${{ inputs.tbb-root }}
        run: |
          if [[ -n "${TBB_ROOT_OPT}" ]]; then
            echo "EXTRA_OPTS=-DTBBROOT=${TBB_ROOT_OPT}" >> "$GITHUB_ENV"
          else
            echo "EXTRA_OPTS=" >> "$GITHUB_ENV"
          fi

      - name: CMake configure - OpenVINO + NPU
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: |
          cmake \
            -G Ninja \
            -D CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
            -D BUILD_SHARED_LIBS=OFF \
            -D OPENVINO_EXTRA_MODULES=$(realpath ${NPU_COMPILER_REPO}) \
            -D ENABLE_LTO=OFF \
            -D ENABLE_FASTER_BUILD=OFF \
            -D ENABLE_CPPLINT=OFF \
            -D ENABLE_TESTS=OFF \
            -D ENABLE_FUNCTIONAL_TESTS=OFF \
            -D ENABLE_SAMPLES=OFF \
            -D ENABLE_JS=OFF \
            -D ENABLE_PYTHON=OFF \
            -D ENABLE_PYTHON_PACKAGING=OFF \
            -D ENABLE_WHEEL=OFF \
            -D ENABLE_OV_ONNX_FRONTEND=OFF \
            -D ENABLE_OV_PYTORCH_FRONTEND=OFF \
            -D ENABLE_OV_PADDLE_FRONTEND=OFF \
            -D ENABLE_OV_TF_FRONTEND=OFF \
            -D ENABLE_OV_TF_LITE_FRONTEND=OFF \
            -D ENABLE_OV_JAX_FRONTEND=OFF \
            -D ENABLE_OV_IR_FRONTEND=ON \
            -D THREADING=TBB \
            -D ENABLE_TBBBIND_2_5=OFF \
            -D ENABLE_SYSTEM_TBB=OFF \
            -D ENABLE_TBB_RELEASE_ONLY=OFF \
            -D ENABLE_HETERO=OFF \
            -D ENABLE_MULTI=OFF \
            -D ENABLE_AUTO=OFF \
            -D ENABLE_AUTO_BATCH=OFF \
            -D ENABLE_TEMPLATE=OFF \
            -D ENABLE_PROXY=OFF \
            -D ENABLE_INTEL_CPU=OFF \
            -D ENABLE_INTEL_GPU=OFF \
            -D ENABLE_NPU_PLUGIN_ENGINE=OFF \
            -D ENABLE_DRIVER_COMPILER_ADAPTER=OFF \
            -D ENABLE_INTEL_NPU_INTERNAL=OFF \
            -D ENABLE_INTEL_NPU_PROTOPIPE=OFF \
            -D BUILD_COMPILER_FOR_DRIVER=ON \
            -D ENABLE_PRIVATE_TESTS=OFF \
            -D ENABLE_NPU_LSP_SERVER=OFF \
            -D CMAKE_TOOLCHAIN_FILE=$(realpath ${OPENVINO_REPO})/cmake/toolchains/onecoreuap.toolchain.cmake \
            -D ENABLE_PDB_IN_RELEASE=ON \
            ${EXTRA_OPTS} \
            ${{ inputs.openvino-cmake-options }} \
            -S ${OPENVINO_REPO} \
            -B ${OPENVINO_BUILD_DIR}

      - name: CMake build - CiD targets
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: |
          cmake \
            --build "${OPENVINO_BUILD_DIR}" \
            --parallel \
            --config "${CMAKE_BUILD_TYPE}" \
            --target npu_driver_compiler compilerTest profilingTest vpuxCompilerL0Test loaderTest

      - name: CMake cpack - CiD target
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: |
          cpack -V \
            --config "${OPENVINO_BUILD_DIR}/CPackConfig.cmake" \
            -C "${CMAKE_BUILD_TYPE}" \
            -G ZIP \
            -B "${CID_PACKAGE_ARTIFACTS_DIR}" \
            -D CPACK_COMPONENTS_ALL=CiD \
            -D CPACK_CMAKE_GENERATOR=Ninja \
            -D CPACK_PACKAGE_FILE_NAME="${CID_PACKAGE_BASE_NAME}"

      - name: CiD Package renaming
        run: |
          mv "${CID_PACKAGE_ARTIFACTS_DIR}/"*.zip \
            "${CID_PACKAGE_ARTIFACTS_DIR}/${CID_PACKAGE_FULL_NAME}"

      - name: Cache CiD artifacts
        if: ${{ inputs.build-cache && !steps.cache-restore.outputs.cache-hit }}
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ${{ env.CID_PACKAGE_ARTIFACTS_DIR }}
          key: ${{ steps.cache-key.outputs.cache-key }}

      - name: Upload CiD package
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          path: ${{ env.CID_PACKAGE_ARTIFACTS_DIR }}/${{ env.CID_PACKAGE_FULL_NAME }}
          name: ${{ env.CID_PACKAGE_FULL_NAME }}

      - name: Set build package name to outputs
        id: set-build-package-name
        run: |
            echo "build-package=${CID_PACKAGE_FULL_NAME}" >> $GITHUB_OUTPUT
      
      - name: Upload asset to existing release tag
        if: ${{ github.event_name != 'pull_request' && inputs.publish-release-assets }}
        env:
          GITHUB_TOKEN: ${{ secrets.release_token || secrets.RELEASE_WRITER_TOKEN }}
        run: |
          NPU_TAG="${{ steps.versions.outputs.npu-compiler-tag }}"
          CID_ASSET="${CID_PACKAGE_ARTIFACTS_DIR}/${CID_PACKAGE_FULL_NAME}"

          gh release upload "$NPU_TAG" "$CID_ASSET" --clobber
          echo "Uploaded $CID_ASSET to release $NPU_TAG"
