name: Linux (Ubuntu 22.04)
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

concurrency:
  group: mlir-linux-${{ github.event_name }}-${{ github.ref_name }}-ubuntu-22
  cancel-in-progress: true

permissions: read-all

jobs:
  MLIR:
    name: MLIR
    uses: ./.github/workflows/job_mlir_linux.yml
    with:
      os: ubuntu_22_04
      build-runner: ubuntu-22.04-16-cores
      test-runner: ubuntu-22.04-8-cores
      run-unit-tests: true
      run-lit-tests: true
      run-compilation-tests: true
