name: Linux (Ubuntu 24.04, Python 3.12)
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.event_name == 'push' && github.run_id || github.ref }}-ubuntu-24
  cancel-in-progress: true

permissions: read-all

jobs:
  Build:
    uses: ./.github/workflows/job_build_and_test_linux.yml
    with:
      runner: 'ubuntu-latest-32-cores'
      event-name: ${{ github.event_name }}
      os: 'ubuntu_24_04'
