name: Linux (Ubuntu 24.04)
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

concurrency:
  group: mlir-linux-${{ github.event_name }}-${{ github.ref_name }}-ubuntu-24
  cancel-in-progress: true

permissions: read-all

jobs:
  MLIR:
    name: MLIR
    uses: ./.github/workflows/job_build_test_mlir_linux.yml
    with:
      build-runner: 'ubuntu-latest-64-cores'
      test-runner: 'ubuntu-latest-8-cores'
      run-tests: false
